variables:
  BIN_PATH: '~/.local/bin'
  PRUNE_DOCKER_CACHE: 'true'

.develop: &develop
  variables:
    VERSION: 'latest'
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

.tag: &tag
  variables:
    VERSION: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

.develop_tag: &develop_tag
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

stages:
  - prepare
  - taskfile
  - release-cli
  - lint-staging
  - build-staging
  - deploy-staging
  - release
  - deploy-prod

prepare:
  <<: *develop_tag
  stage: prepare
  script:
    - ls -l /var/run/docker.sock
    - docker --version | grep "Docker version" || (echo "Docker socket not binded."; exit
      1)

taskfile:
  <<: *develop_tag
  stage: taskfile
  before_script:
    - apk add --no-cache curl
    - curl --version | grep "curl" || (echo "Curl not installed."; exit 1)
  script:
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ${BIN_PATH}
  after_script:
    - ${BIN_PATH}/task --version | grep "Task version" || (echo "Taskfile not installed.";
      exit 1)
  artifacts:
    paths:
      - ${BIN_PATH}

release-cli:
  <<: *tag
  stage: release-cli
  before_script:
    - apk add --no-cache curl
    - curl --version | grep "curl" || (echo "Curl not installed."; exit 1)
    - apk add --no-cache sudo
    - sudo --version | grep "Sudo version" || (echo "Sudo not installed."; exit 1)
  script:
    - curl --location --output ${BIN_PATH}/release-cli
      "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
    - sudo chmod +x ${BIN_PATH}/release-cli
  after_script:
    - ${BIN_PATH}/release-cli -v | grep "release-cli version" || (echo "release-cli not
      installed."; exit 1)
  artifacts:
    paths:
      - ${BIN_PATH}

lint-staging:
  <<: *develop
  stage: lint-staging
  script:
    - ${BIN_PATH}/task docker:build -- lint
  dependencies:
    - taskfile

build-staging:
  <<: *develop
  stage: build-staging
  script:
    - ${BIN_PATH}/task docker:compose -- down
    - ${BIN_PATH}/task docker:build
    - ${BIN_PATH}/task docker:push
  dependencies:
    - taskfile

deploy-staging:
  <<: *develop
  stage: deploy-staging
  script:
    - ${BIN_PATH}/task docker:compose -- up -d --no-build
  after_script:
    - |
      if [ "${PRUNE_DOCKER_CACHE}" = "true" ]; then
        docker system prune -f && docker builder prune --all --force
      fi
  environment:
    name: staging
    url: http://vsrvfeia0h-86.vsb.cz:${NODE_PORT}/
  dependencies:
    - taskfile
    - build-staging

release:
  <<: *tag
  stage: release
  variables:
    DATETIME_FORMAT: '+%Y-%m-%d %H:%M:%S'
  before_script:
    - apk add --no-cache coreutils
    - echo $VERSION
    - echo $CI_COMMIT_TAG
    - PUSH_OUTPUT=$(${BIN_PATH}/task docker:push)
    - IMAGE_NAME=$(echo ${PUSH_OUTPUT} | grep -o "image-provider[^ ]*" | tr -d ":" | sort
      -u | tail -n 1)
    - DIGEST_NAME=$(echo ${PUSH_OUTPUT} | grep -o "sha256[^ ]*" | tr ":" "-" | tail -n 1)
    - DATETIME="$(date -d "${CI_COMMIT_TIMESTAMP}" "${DATETIME_FORMAT}")"
  script:
    - >-
      ${BIN_PATH}/release-cli create --tag-name "${CI_COMMIT_TAG}" --name
      "${CI_COMMIT_TAG}" --description " # 🚀 Release ${CI_COMMIT_TAG}

      **Release Date:** ${DATETIME}

      ### 🐳 Docker image

      -
      [${IMAGE_NAME}](https://hub.docker.com/layers/jav0032/retina/${IMAGE_NAME}/images/${DIGEST_NAME})
      "
  dependencies:
    - taskfile
    - release-cli

deploy-prod:
  <<: *tag
  stage: deploy-prod
  script:
    - echo "Deploying to production... [WIP]"
  dependencies:
    - release
