name: image-provider

services:
  image-provider:
    container_name: image-provider
    image: ${DOCKER_IMAGE:-retina/image-provider}:${DOCKER_TAG:-latest}
    profiles: [prod]
    build:
      target: ${DOCKER_TARGET:-final}
      args:
        DOCKER_TAG: ${DOCKER_TAG:-latest}
        IMAGE_PROVIDER_PORT: ${IMAGE_PROVIDER_PORT:?errorHandler}
    environment:
      IMAGE_PROVIDER_DEBUG: true
      IMAGE_PROVIDER_PORT: ${IMAGE_PROVIDER_PORT:?errorHandler}
      IMAGE_PROVIDER_UPLOAD_PATH: ${IMAGE_PROVIDER_UPLOAD_PATH:?errorHandler}
      IMAGE_PROVIDER_UPLOAD_SIZE: ${IMAGE_PROVIDER_UPLOAD_SIZE:?errorHandler}
      IMAGE_PROVIDER_SSL_CERT_PATH: ${IMAGE_PROVIDER_SSL_CERT_PATH:?errorHandler}
      IMAGE_PROVIDER_SSL_KEY_PATH: ${IMAGE_PROVIDER_SSL_KEY_PATH:?errorHandler}
    ports:
      - ${IMAGE_PROVIDER_PORT:?errorHandler}:${IMAGE_PROVIDER_PORT:?errorHandler}
    restart: unless-stopped
    volumes:
      - ${IMAGE_PROVIDER_UPLOAD_PATH:?errorHandler}:${IMAGE_PROVIDER_UPLOAD_PATH:?errorHandler}
      - ${IMAGE_PROVIDER_SSL_CERT_PATH:?errorHandler}:${IMAGE_PROVIDER_SSL_CERT_PATH:?errorHandler}
      - ${IMAGE_PROVIDER_SSL_KEY_PATH:?errorHandler}:${IMAGE_PROVIDER_SSL_KEY_PATH:?errorHandler}

  healthcheck:
    container_name: healthcheck
    image: alpine
    profiles: [prod]
    restart: no
    depends_on:
      image-provider:
        condition: service_healthy
    command: ["sh", "-c", "echo 'All services are healthy, exiting.'"]
