name: image-provider

services:
  redoc:
    container_name: redoc
    image: redocly/redoc:v2.1.4
    environment:
      SPEC_URL: "http://${NODE_HOSTNAME}:${NODE_PORT}/docs"
      PAGE_TITLE: "ReDoc - Image Provider"
    ports:
      - ${NODE_REDOC_PORT}:80
    restart: unless-stopped