name: retina-image-provider

services:
  image-provider:
    container_name: image-provider
    image: ${DOCKER_IMAGE:-retina/image-provider}:${DOCKER_TAG:-latest}
    profiles: [prod]
    build:
      target: ${DOCKER_TARGET:-final}
      args:
        DOCKER_TAG: ${DOCKER_TAG:-latest}
        IMAGE_PROVIDER_PORT: ${IMAGE_PROVIDER_PORT:?error}
    environment:
      IMAGE_PROVIDER_DEBUG: true
      IMAGE_PROVIDER_PORT: ${IMAGE_PROVIDER_PORT:?error}
      IMAGE_PROVIDER_UPLOAD_SIZE: ${IMAGE_PROVIDER_UPLOAD_SIZE:?error}
      IMAGE_PROVIDER_SSL_CERT_PATH: ${IMAGE_PROVIDER_SSL_CERT_PATH:?error}
      IMAGE_PROVIDER_SSL_KEY_PATH: ${IMAGE_PROVIDER_SSL_KEY_PATH:?error}
    # noinspection ComposeUnknownValues
    ports:
      - ${IMAGE_PROVIDER_PORT:?error}:${IMAGE_PROVIDER_PORT:?error}
    restart: unless-stopped
    tty: true
    volumes:
      - ${IMAGE_PROVIDER_SSL_CERT_PATH:?error}:${IMAGE_PROVIDER_SSL_CERT_PATH:?error}
      - ${IMAGE_PROVIDER_SSL_KEY_PATH:?error}:${IMAGE_PROVIDER_SSL_KEY_PATH:?error}
      - image-data:/var/lib/image_provider

  image-provider-healthcheck:
    container_name: image-provider-healthcheck
    image: alpine
    profiles: [prod]
    restart: no
    depends_on:
      image-provider:
        condition: service_healthy
    command: ["sh", "-c", "echo 'All services are healthy, exiting.'"]

volumes:
  image-data:
    external: true
    name: image-provider-data