FROM node:20.6.1 as base

WORKDIR /app

EXPOSE 8000

COPY . .

RUN corepack enable
RUN yarn set version stable
RUN yarn config set nodeLinker node-modules
RUN yarn install
RUN yarn build

FROM 

