# base stage
FROM retina/image-provider:latest AS base

ARG DOCKER_TAG

RUN apk add --no-cache --update jq && \
    jq --arg DOCKER_TAG "${DOCKER_TAG}" 'walk(if type == "string" then gsub("{{VERSION}}"; $DOCKER_TAG) else . end)' \
      docs/openapi.json > docs/openapi.tmp.json && \
    mv docs/openapi.tmp.json docs/openapi.json && \
    sed -i "s/{{VERSION}}/${DOCKER_TAG}/g" static/redoc.html

# prod stage
FROM retina/image-provider:latest AS final

ARG DOCKER_TAG

COPY --from=base /app/. .

# meta additions
LABEL org.opencontainers.image.title="image-provider"
LABEL org.opencontainers.image.description="Express API for upload and serve retina images"
LABEL org.opencontainers.image.vendor="VSB"
LABEL org.opencontainers.image.version="${DOCKER_TAG}"
LABEL org.opencontainers.image.base.name="node:alpine3.19"

# for debug purpose only
# CMD ["sleep", "infinity"]