version: 3

dotenv: [".env.local"]

tasks:
  ## development tasks ##
  init:
    desc: >
      Initialize express project for development |
      Usage: task init (i) [-- hard]
    aliases: [i]
    platforms: [linux]
    cmds:
      - >
        {{if eq .CLI_ARGS "hard"}}
          rm -rf bun.lock
        {{end}}
      - rm -rf node_modules
      - bun install
  ## ----------------- ##

  ## deployment tasks ##
  docker:build:
    desc: >
      Build docker image for deployment |
      Usage: task docker:build (d:b) [DOCKER_TARGET=lint/final, default final]
    summary: |
      Usage: task docker:build (d:b) [DOCKER_TARGET=lint/final, default final]
      
      Build docker image for deployment
      
      Optional variables:
        DOCKER_TARGET     Defines target for docker image stage
      
      Examples:
        task docker:build
        task docker:build DOCKER_TARGET=lint
        task docker:build DOCKER_TARGET=final
    aliases: [d:b]
    platforms: [linux]
    env:
      DOCKER_TARGET: '{{.DOCKER_TARGET}}' # pass taskfile variable to environment
      COMPOSE_BAKE: 'true'
    cmds:
      - docker compose --profile prod build
      - defer: |
          {{if and (ne .DOCKER_TARGET "final") (not (or (eq .DOCKER_TARGET nil) (eq .DOCKER_TARGET "")))}}
            docker rmi -f retina/image-provider
          {{end}}

  docker:deploy:
    desc: >
      Run builded docker image in container |
      Usage: task docker:deploy (d:d)
    summary: |
      Usage: task docker:deploy (d:d)
      
      Run builded docker image in container 
      
      Examples:
        task docker:deploy
    aliases: [d:d]
    platforms: [linux]
    cmd: docker compose --profile prod up -d --no-build --pull never
  ## ---------------- ##