version: 3

vars:
  DATETIME: '{{now | date "2006-01-02 15:04:05"}}'
  VERSION: 'staging'

env:
  DATETIME: '{{.DATETIME}}'
  VERSION: '{{.VERSION}}'

dotenv: ['.env']

tasks:
  ## development tasks ##
  init:
    desc: Initialize nodejs project for development
    aliases: [i]
    cmds:
      - rm -rf bun.lockb
      - rm -rf node_modules
      - bun install

  docker:dev:
    desc: Run compose for dependent service for development
    aliases: [d:d]
    cmds:
      - docker compose -f ${PWD}/compose.dev.yml up --force-recreate --build
      - defer: docker compose -f ${PWD}/compose.dev.yml down
      - defer: docker image prune -f
    interactive: true
  ## ----------------- ##

  ## deployment tasks ##
  docker:build:
    desc: Build docker image for deployment
    aliases: [d:b]
    env:
      TARGET: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}prod{{end}}'
    cmds:
      - docker compose build
      - defer: docker image prune -f
      - defer: >
          {{if .CLI_ARGS}}
          docker image rm jav0032/retina:image-provider-{{.VERSION}}
          {{end}}

  docker:compose:
    desc: Run compose for deployment with defined variables
    aliases: [d:c]
    cmds:
      - docker compose {{.CLI_ARGS}}
      - defer: docker image prune -f
    requires:
      vars: [CLI_ARGS]

  docker:push:
    desc: Push builded docker image to docker hub
    aliases: [d:p]
    cmds:
      - echo "{{.DOCKER_PASSWD}}" | docker login -u "{{.DOCKER_USER}}" --password-stdin
      - |
        {{if .RELEASE_VERSION}}
        docker pull jav0032/retina:image-provider-{{.VERSION}}
        docker tag jav0032/retina:image-provider-{{.VERSION}} jav0032/retina:image-provider-{{.RELEASE_VERSION}}
        docker push jav0032/retina:image-provider-{{.RELEASE_VERSION}}
        docker rmi -f jav0032/retina:image-provider-{{.RELEASE_VERSION}}
        {{else}}
        docker push jav0032/retina:image-provider-{{.VERSION}}
        {{end}}
  ## ---------------- ##