version: "3"

vars:
  SHELL_START: '{{if eq .OS "Windows_NT"}}wsl bash -c "{{end}}'
  SHELL_END: '{{if eq .OS "Windows_NT"}}"{{end}}'
  DATETIME: '{{now | date "2006-01-02 15:04:05"}}'

env:
  VERSION: latest
  DEBUG: true
  HOSTNAME: http://vsrvfeia0h-86.vsb.cz/
  PORT: 8000
  UPLOAD_DIR: /tmp/image_provider/uploads
  APISCHEMA_DIR: /tmp/image_provider
  UPLOAD_SIZE: 1000
  REDOC_HOSTNAME: http://vsrvfeia0h-86.vsb.cz/
  REDOC_PORT: 80

tasks:
  ## development tasks ##
  init:
    desc: Initialize parcel project for development
    aliases: [i]
    cmds:
      - corepack enable
      - yarn install

  init:reinstall:
    desc: Reinitialize parcel project for development (delete cache & node_modules)
    aliases: [i:r]
    cmds:
      - task: clear
      - task: init

  init:reinit:
    desc: Reinitialize parcel project for development (delete all)
    aliases: [i:re]
    cmds:
      - task: prune
      - task: init

  clear:
    desc: Clear node_modules of all yarn workspaces installs
    aliases: [c]
    internal: true
    cmds:
      - "{{.SHELL_START}}rm -rf .yarn{{.SHELL_END}}"
      - "{{.SHELL_START}}rm -rf .parcel-cache{{.SHELL_END}}"
      - "{{.SHELL_START}}rm -rf node_modules{{.SHELL_END}}"

  prune:
    desc: Prune node_modules of yarn installs with lock file
    aliases: [p]
    internal: true
    cmds:
      - "{{.SHELL_START}}rm -rf .yarn{{.SHELL_END}}"
      - "{{.SHELL_START}}rm -rf .parcel-cache{{.SHELL_END}}"
      - "{{.SHELL_START}}rm -rf yarn.lock{{.SHELL_END}}"
      - "{{.SHELL_START}}rm -rf node_modules{{.SHELL_END}}"

  dev:compose:up:
    desc: Run compose for dependent service for development
    aliases: [d:c:d]
    dotenv: [".env"]
    cmd: "{{.SHELL_START}}STAGE='-dev' docker compose --profile dev up -d{{.SHELL_END}}"

  dev:compose:down:
    desc: Stop compose for dependent service for development
    aliases: [d:c:d]
    dotenv: [".env"]
    cmd: "{{.SHELL_START}}STAGE='-dev' docker compose --profile dev down{{.SHELL_END}}"

  ## ----------------- ##

  ## deployment tasks ##
  docker:build:
    desc: Build docker image for deployment
    aliases: [d:b]
    cmds:
      - >
        docker build 
        --build-arg DATETIME='{{.DATETIME}}'
        --build-arg VERSION='{{.VERSION}}'
        -t jav0032/retina:image-provider-{{.VERSION}}
        -f Dockerfile .
      - docker image prune -f

  docker:compose:up:
    desc: Run compose for builded images
    aliases: [d:c]
    cmds:
      - "{{.SHELL_START}}mkdir -p {{.UPLOAD_DIR}}{{.SHELL_END}}"
      - "{{.SHELL_START}}mkdir -p {{.APISCHEMA_DIR}}{{.SHELL_END}}"
      - "{{.SHELL_START}}STAGE='' docker compose --profile deploy up -d{{.SHELL_END}}"

  docker:compose:down:
    desc: Down compose for builded images
    aliases: [d:c]
    cmds:
      - "{{.SHELL_START}}STAGE='' docker compose --profile deploy down{{.SHELL_END}}"
  ## ---------------- ##